@echo off
setlocal enabledelayedexpansion

echo ========================================
echo  Build Both Brands (ASMRTOP + Public)
echo ========================================

set DRIVER_DIR=d:\Autigravity\wdm2vst\ASMRTOP_Driver_V3
set SIGN_BASE=D:\Autigravity\sgin\wdm2vst
set MSBUILD="C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"

taskkill /f /im msbuild.exe >nul 2>&1

:: ============================================
:: 1. Build ASMRTOP branded version
:: ============================================
echo.
echo [1/4] Setting brand: ASMRTOP...
cd /d "%DRIVER_DIR%"
powershell -ExecutionPolicy Bypass -File set_brand.ps1 asmrtop

echo [2/4] Building ASMRTOP brand...
:: Build only Main project (produces .sys), skip package project (inf2cat fails on renamed .sys)
call %MSBUILD% "Source\Main\Main.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:InfVerif_Enable=false /v:minimal /m
if errorlevel 1 (echo MAIN BUILD FAILED & goto fail)

echo Copying ASMRTOP files...
mkdir "%SIGN_BASE%\asmrtop" 2>nul
:: .sys compiled as VirtualAudioDriver.sys, rename to match INF
copy /y "Source\Main\x64\Release\VirtualAudioDriver.sys" "%SIGN_BASE%\asmrtop\ASMRTOPAudioRouter.sys"
:: .inf generated by stampinf from .inx
copy /y "x64\Release\VirtualAudioDriver.inf" "%SIGN_BASE%\asmrtop\ASMRTOPAudioRouter.inf"
if not exist "x64\Release\VirtualAudioDriver.inf" (
    :: Fallback: copy from Main output
    copy /y "Source\Main\x64\Release\VirtualAudioDriver.inf" "%SIGN_BASE%\asmrtop\ASMRTOPAudioRouter.inf"
)
echo ASMRTOP brand done!

:: ============================================
:: 2. Build Public version
:: ============================================
echo.
echo [3/4] Setting brand: PUBLIC...
powershell -ExecutionPolicy Bypass -File set_brand.ps1 public

echo [4/4] Building PUBLIC brand...
call %MSBUILD% "Source\Main\Main.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:InfVerif_Enable=false /v:minimal /m
if errorlevel 1 (echo MAIN BUILD FAILED & goto fail)

echo Copying PUBLIC files...
mkdir "%SIGN_BASE%\gongkai" 2>nul
copy /y "Source\Main\x64\Release\VirtualAudioDriver.sys" "%SIGN_BASE%\gongkai\VirtualAudioRouter.sys"
copy /y "x64\Release\VirtualAudioDriver.inf" "%SIGN_BASE%\gongkai\VirtualAudioRouter.inf"
if not exist "x64\Release\VirtualAudioDriver.inf" (
    copy /y "Source\Main\x64\Release\VirtualAudioDriver.inf" "%SIGN_BASE%\gongkai\VirtualAudioRouter.inf"
)
echo PUBLIC brand done!

:: ============================================
:: Summary
:: ============================================
echo.
echo ========================================
echo  BUILD COMPLETE
echo ========================================
echo.
echo ASMRTOP (branded):
dir "%SIGN_BASE%\asmrtop\*.*" 2>nul
echo.
echo PUBLIC:
dir "%SIGN_BASE%\gongkai\*.*" 2>nul
echo.
echo Next: sign each folder's .sys + .inf to produce matching .cat
echo   asmrtop: ASMRTOPAudioRouter.cat
echo   gongkai: VirtualAudioRouter.cat
echo.
pause
exit /b 0

:fail
echo.
echo BUILD FAILED!
pause
exit /b 1
